### ISSUE TITLE
In 1.12.2, drinking potions does not work. tested with this mod and nothing else

### ISSUE THREAD

**Issue by PrinceOfAmber** [orbwoi/UniversalRemote#13]
Here is latest.log
https://pastebin.com/DnuQZEvv

Looks like something about a coremod / reflection change

java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.client.gui.GuiDownloadTerrain.<init>(Lnet/minecraft/client/network/NetHandlerPlayClient;)V

**Comment by orbwoi** [comment]
Ha- you are very perceptive. :)

Indeed, this mod unfortunately has significant use of reflection deep into Minecraft and Forge due to lack of support for cross dim GUI. Mojang changed the parameters to the constructor of the Loading Terran GUI.

The 1.12-0.9.5 update should fix this as well as many other things.
