### ISSUE TITLE
Incompatibility with standard fake player checks.

### ISSUE THREAD

**Issue by darkhax** [orbwoi/UniversalRemote#21]
Hello, 

Your mod replaces the vanilla player entity with your own. Doing this causes massive issues for mods that have checks for fake players. Here is an example of a typical fake player check. 

```java
    public static boolean isPlayerReal (Entity player) {
        return player != null && player.world != null && player.getClass() == EntityPlayerMP.class;
    }
```

The reason you check for that exact class is because FakePlayer extends EntityPlayerMP, and there are several mods with their own implementations of a fake player that do not use Forge's FakePlayer class. 

This issue makes your mod incompatible with nearly all mods that [depend on Bookshelf](https://minecraft.curseforge.com/projects/bookshelf/relations/dependents?filter-related-dependents=3), and all of the other mods which do this type of check such as [MLCore](https://github.com/MatchlighterMods/MLCore) and it's dependents, [MDECore](https://github.com/MattDahEpic/MDECore/blob/f29abac1d7e92a2804e6714a86a2598695eb1127/src/main/java/com/mattdahepic/mdecore/helpers/PlayerHelper.java) and it's depdents, [Spontaneous Collections](https://github.com/BlueAgent/Spontaneous-Collection/blob/d09a7597d65b2a04db4ebe95fe0808ea1e618c74/src/main/java/spontaneouscollection/common/helper/PlayerHelper.java), and many other mods.

**Comment by orbwoi** [comment]
Hello darkhax, sorry about the delayed response- been busy irl last few days.

Frankly, I agree with you about this situation, but let me explain a little bit about the constraints I am under and best in class object oriented programming practices.

Essentially, the universal remote mode is an extended player functionality mod. In other words, it wants to add a new core feature to the Minecraft engine (rather than build on existing forge features) and expose that though as an easy to use remote. It does this by spoofing the player server and client position and look vector to the targeted mod in order to open the GUI from anywhere.

An older implementation did not expand the base player class held by Minecraft itself. However, many mods do range checks either in events or simply acquire the player object from somewhere other than the passed in arguments. In order to support multiple important mods, I decided to extend the base player object of Minecraft using reflection. This actually works quite well since I was able to find a way to distinguish which mod was asking for player position and lie about it only to the target mod and only while the GUI was still open.

Unfortunately, as you say, this does trigger some fake player checks if written as you suggest above. I did  encounter a check like that in IC2 but IC2 only uses that check only under certain circumstances and I was able to ensure it worked in the normal way (without a remote). I tested with every mod in ATM3 a while back and wasn't able to find any mods using that style of fake player check so I was hoping it wasn't very common.

Now, in regards to the check itself. I understand the reasoning for it and the fact that many mods use this style of check. However, as a senior software engine and mentor in my day job, I want to say that it isn't great code. If one of my students or employees sent me code like that, I would make then re-write it. The reason is that violates the [open-closed principle](https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#toc-open-closed-principle) of SOLID object oriented programming. The goal is to check if this is a fake player so that we ensure the target gameplay element only works for the real player and not his devices. That is fine. However, the check doesn't actually do that. It just ensures the player's functionality isn't extend or modified. Those two checks are not the same thing.

We should allow players to be extended but still block fake ones. An example of a different implementation which is not subject to this constraint would be something like the following:

`    public static boolean isPlayerReal (EntityPlayerMP player) {
    	return FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList().getPlayers().contains(player);
    }`

Ultimately, I think it might be best for forge to provide an IsFakePlayer API which can be updated and standard across all mods.

That said, I would love to be compatible with current mods like the ones you mention above without having them all update their code. Unfortunately I cannot think of a good way right now. I suppose I could add an exceptions list for mods in the config, but that isn't really a good long term solution. If you have any suggestions please let me know.

**Comment by darkhax** [comment]
Thanks for the thoughtful response on this issue. I am aware that this code violates open-closed, and that's not something I am happy about. Unfortunately it has been a necessary evil when working with other mods. 

The solution you have come up with is a seemingly acceptable one, however in the past there have been some mods that add their fake player to the player list. In one specific example they were using this to add messages to the player list gui from the server. I haven't seen any mods that do this in 1.12.2, but there is always the chance that those mods will be updated or new mods will take their place. Because of this, it's not a good long term solution on my end. 

With all of this in mind, Forge has recently accepted [this](https://github.com/MinecraftForge/MinecraftForge/pull/4438/files) PR which does a check similarly to the way described in my initial comment. I think that this type of check being used in Forge is good enough for me to point to when it gets brought up.

**Comment by orbwoi** [comment]
Thanks for the thoughtful reply. :)

Interesting- so they used the player list to display a message on the player list... that's an interesting approach. Has any mod you can think of ever BOTH done that AND had a fake player machine using the same player object? It is possible to write something that breaks this- though it seem unlikely.

Also, I notice that the PR in forge is doing a _blacklist_ check for FakePlayer not a whitelist for the default player class. They didn't break open/closed with that patch.

I haven't tried to make a pull request to forge yet. Before then, I need to more carefully consider exactly what I should ask them to put in forge and present it as an api that any modder can use. Also, it needs to not break if more than one person wants to use it. Are the pull reviewers for forge fairly friendly to newcomers?

It would be nice to finally add the real ability for the client to load chunks of other worlds (without the player being in that world) and get updates on them for looking through live portals to other dimensions (or remote GUI access like in my mod).

**Comment by orbwoi** [comment]
Closing issue since your change resolved the conflict.
